package lab9;

import java.util.Random;

/**
 * Cacu Razvan GR-2023
 * Write a Java application with a thread that generates 30 random numbers between 0 and 30. Another thread displays
 * the area of the circles having as radiuses the values divisible by 3 generated by the first thread.
 */

class RandomNumberGeneratorThread extends Thread {
    private final Random random = new Random();

    @Override
    public void start() {
        for (int i = 0; i < 30; i++) {
            int radius = random.nextInt(100);
            System.out.println("Generated value: " + radius);
            if (radius % 3 == 0)
                CircleAreaDisplayThread.addRadius(radius);
        }

    }
}

class CircleAreaDisplayThread extends Thread {
    private static int count = 0;
    private static final int[] radii = new int[30];

    @Override
    public void start() {
        while (count >= 0) {
            if (radii[count] % 3 == 0 && radii[count] > 0) {
                double area = Math.PI * Math.pow(radii[count], 2);
                System.out.println("Circle area with radius " + radii[count] + " is " + area);
            }
            count--;
        }
    }

    public static synchronized void addRadius(int radius) {
        radii[count] = radius;
        count++;
    }

}

public class Lab9Prb2 {
    public static void main(String[] args) {
        RandomNumberGeneratorThread randomNumberGeneratorThread = new RandomNumberGeneratorThread();
        CircleAreaDisplayThread circleAreaDisplayThread = new CircleAreaDisplayThread();

        randomNumberGeneratorThread.start();
        circleAreaDisplayThread.start();
    }
}
